"""
Generate the flashcard deck pages from src/lib/flashcards.ts.

The deck list, the card counts and the topic lines all live in the data file.
Writing them again by hand is how an index comes to claim ten cards for a deck
that has nine.

    python3 scripts/docs/build_flashcard_pages.py
"""

from __future__ import annotations

import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "src/content/docs/resources/flashcards"


def read_decks() -> list[dict]:
    """Ask Node for the deck metadata, so there is one source of truth."""
    script = """
    import { DECKS, TOTAL_CARDS } from './src/lib/flashcards.ts';
    const out = DECKS.map(d => ({
      slug: d.slug, title: d.title, label: d.label, blurb: d.blurb,
      topics: d.topics, chapter: d.chapter, count: d.cards.length,
    }));
    console.log(JSON.stringify({ decks: out, total: TOTAL_CARDS }));
    """
    result = subprocess.run(
        ["node", "--experimental-strip-types", "--input-type=module", "-e", script],
        cwd=ROOT, capture_output=True, text=True,
    )
    if result.returncode != 0:
        sys.exit(f"could not read the decks:\n{result.stderr.strip()[-1500:]}")
    line = [l for l in result.stdout.splitlines() if l.startswith("{")][-1]
    return json.loads(line)


def deck_page(deck: dict) -> str:
    return f'''---
title: "{deck['title']} Flashcards"
description: "Retrieval practice for the {deck['title']} material: {deck['count']} cards covering {', '.join(deck['topics'][:3]).lower()} and more."
---

import FlashcardDeck from '../../../../components/flashcards/FlashcardDeck.astro';
import {{ deckOf }} from '../../../../lib/flashcards';

{{/* GENERATED by scripts/docs/build_flashcard_pages.py. Edit the cards in
    src/lib/flashcards.ts and rebuild. */}}

**{deck['count']} cards.** {deck['blurb']}

Every card shows its question first. Reveal one at a time to test yourself, or
reveal all of them to use the deck as a revision sheet.

<FlashcardDeck deck={{deckOf('{deck['slug']}')}} />

[Back to all decks](/resources/flashcards/) ·
[Read the {deck['title']} material]({deck['chapter']})
'''


def index_page(decks: list[dict], total: int) -> str:
    rows = "\n".join(
        f"| [{d['title']}](/resources/flashcards/{d['slug']}/) | {d['count']} cards | "
        f"{', '.join(d['topics'])} |"
        for d in decks
    )
    return f'''---
title: "Interactive Flashcards"
description: "Retrieve the key concepts, equations, and intuitions from memory. {total} cards across five decks."
---

import Callout from '../../../components/ui/Callout.astro';

{{/* GENERATED by scripts/docs/build_flashcard_pages.py. Edit the cards in
    src/lib/flashcards.ts and rebuild. */}}

**Retrieve the key concepts, equations, and intuitions from memory.**

{total} cards across five decks. Each deck opens with every card visible, so
you can test yourself one card at a time or reveal the whole deck and read it
as a revision sheet.

<div class="table-scroll">

| Deck | Size | Covers |
| --- | --- | --- |
{rows}
</div>

<Callout tone="observe" title="How to get the most from these" icon="compass">
Read the question, answer it in your head or out loud, and only then reveal the
card. The effort of retrieving something you half remember is what makes it
stick, and skipping straight to the answer feels like learning without being
it.

These cards test recall. The knowledge checks, worksheets and labs are where
reasoning, calculation and experimentation happen.
</Callout>
'''


def main() -> None:
    data = read_decks()
    decks, total = data["decks"], data["total"]
    OUT.mkdir(parents=True, exist_ok=True)

    index = ROOT / "src/content/docs/resources/flashcards.mdx"
    index.write_text(index_page(decks, total))
    print(f"  wrote {index.relative_to(ROOT)}")

    for deck in decks:
        target = OUT / f"{deck['slug']}.mdx"
        target.write_text(deck_page(deck))
        print(f"  wrote {target.relative_to(ROOT)}  ({deck['count']} cards)")

    print(f"\n{len(decks)} decks, {total} cards")


if __name__ == "__main__":
    main()
